// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int nTimes = Integer.parseInt(args[0]);
		int counterBiggerThanHalf = 0;
		int counterSmallerThanHalf = 0;
		double ratio;

		double randomNumber;
		for (int i = 1; i <= nTimes; i++) {
			randomNumber = Math.random();
			if (randomNumber > 0.5) {
				counterBiggerThanHalf++;
			} else {
				counterSmallerThanHalf++;
			}
		}

		if (counterSmallerThanHalf > 0) {
			ratio = (double) counterBiggerThanHalf / counterSmallerThanHalf;
			System.out.println("> 0.5: " + counterBiggerThanHalf);
			System.out.println("<= 0/5: " + counterSmallerThanHalf);
			System.out.println("Ratio: " + ratio);
		} else { // No Ratio
			System.out.println("> 0.5: " + counterBiggerThanHalf);
			System.out.println("<= 0/5: " + counterSmallerThanHalf);
		}
	
	}
}
